#!/bin/sh

# tester <binary name> <performance | functional>
# for example: ./tester reverse_bytes performance

test_dir=./test_files
prog="$1"
progname=$(basename "$1")

mkdir -p "$test_dir"

dd if=/dev/urandom of="$test_dir/small.bin" bs=1K count=1 >/dev/null 2>&1
dd if=/dev/urandom of="$test_dir/medium.bin" bs=1M count=1 >/dev/null 2>&1
dd if=/dev/urandom of="$test_dir/big.bin" bs=5M count=1 >/dev/null 2>&1

test_files="small.bin medium.bin big.bin"
if [ "$2" = "performance" ]; then
    echo "PROGRAM: $progname PERFORMANCE TEST"
    for test_file in $test_files; do
        base_path="$test_dir/$test_file"
        printf "$test_file took %s seconds\n" "$(
            /usr/bin/time -f '%e' \
                "$prog" "$base_path" "$base_path.${progname}_rev" 2>&1
        )"
    done
elif [ "$2" = "functional" ]; then
    echo "PROGRAM: $progname FUNCTIONAL TEST"
    for test_file in $test_files; do
        base_path="$test_dir/$test_file"
        "$prog" "$base_path" "$base_path.${progname}_rev"
        "$prog" "$base_path.${progname}_rev" "$base_path.${progname}_rev_rev"
        diff -s "$base_path" "$base_path.${progname}_rev_rev"
    done
fi
